image: "mspteam/node:12.4.0-git"
stages:
- deploy
Production:
  stage: deploy
  script:
    - npm install
    - npm run build
#   - yarn install
#   - yarn workspace web build
    - aws configure set aws_access_key_id $PROD_AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $PROD_AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws configure set preview.cloudfront true
    - aws s3 rm s3://$S3_BUCKET_NAME --region us-east-1 --exclude ""
    - aws s3 sync ./build s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /\*
  variables:
    S3_BUCKET_NAME: ytrend
    AWS_DEFAULT_REGION: us-east-1
    CLOUDFRONT_ID: E1N48ARBOUP0BB
  only:
  - master
  environment:
    name: master